### PR TITLE
Fix to support current firmwares

### PR DESCRIPTION
**Pull request by CidVonHighwind**
@lvonasek can this be merged or are there changes needed?

### CODE REVIEW

**Comment by lvonasek** [comment]
I had to change the project structure because I am not Windows user and your repository setup works only on Android Studio under Windows.

The commits to support Android 12 are:
https://github.com/lvonasek/VirtualBoyQuest/commit/e720ab38bc26cab849bd7bf6ba2e51521209eef7
https://github.com/lvonasek/VirtualBoyQuest/commit/511d42aa159ca1a17ecc268b8e65d9d6b5d1d47c

Feel free to merge it. Will you restore the SideQuest listing or shall I create a new one?

**Comment by CidVonHighwind** [comment]
Okay I will just merge the two commits and restore the SideQuest listing. It is currently just set to private.

**Comment by lvonasek** [comment]
Ok, perfect.

**Comment by Hadlock** [comment]
Is there an ETA on this

**Comment by CidVonHighwind** [comment]
> 

Hopefully by the end of the week.

**Comment by OzzyHelix** [comment]
LGTM

**Pull request closed without merging**
